// ══════════════════════════════════════════════════════════════════════════════
// lib/routes.ts — Typed route name registry
// ══════════════════════════════════════════════════════════════════════════════
//
// Single source of truth for every route name registered in App.tsx
// (Stack.Screen / Tab.Screen). Two purposes:
//
//   1. Compile-time safety. Use Routes.Foo in place of "Foo" string literals
//      at navigation.navigate() call sites — typos become TypeScript errors
//      instead of runtime "no screen named X" warnings. The RootRoute type
//      below is the union of every valid string literal.
//
//   2. CI verification. scripts/check-dead-routes.sh greps for
//      navigation.navigate("X") calls anywhere in the codebase, extracts X,
//      and fails if X is not present here. Catches typos even in code that
//      hasn't migrated to Routes.X yet.
//
// To add a new route: register it in App.tsx as a <Stack.Screen> or
// <Tab.Screen>, then add the matching entry below. Both must agree or the
// check-dead-routes.sh script will fail CI.
//
// To delete a route: remove the <Stack.Screen> registration AND the entry
// here. The check-dead-routes.sh script will then flag any remaining
// navigate("...") call sites that still reference it — those need to be
// fixed or removed before the registration disappears from production.
//
// Generated from App.tsx on 2026-05-27. Kept current by hand thereafter.
// ══════════════════════════════════════════════════════════════════════════════

/**
 * Every route name registered in the app, keyed by name. Use `Routes.X` at
 * navigation.navigate() call sites instead of string literals.
 */
export const Routes = {
  AboutApp: "AboutApp",
  AdminModeration: "AdminModeration",
  AIJobsHealth: "AIJobsHealth",
  PlatformAuditTrail: "PlatformAuditTrail",
  AccessRestricted: "AccessRestricted",
  AccountTiersExplained: "AccountTiersExplained",
  Action: "Action",
  ActiveSessions: "ActiveSessions",
  ActivityEditor: "ActivityEditor",
  AddFunds: "AddFunds",
  AddRecipient: "AddRecipient",
  AdminDashboard: "AdminDashboard",
  AdminSettings: "AdminSettings",
  AdminTemplateQueue: "AdminTemplateQueue",
  AdminVerificationQueue: "AdminVerificationQueue",
  SubmitTemplate: "SubmitTemplate",
  VerificationMap: "VerificationMap",
  AdvanceDetailsV2: "AdvanceDetailsV2",
  AdvanceHubV2: "AdvanceHubV2",
  AdvanceSettings: "AdvanceSettings",
  AuditTrail: "AuditTrail",
  AuthCallback: "AuthCallback",
  AutopaySetup: "AutopaySetup",
  CircleAutopayManagement: "CircleAutopayManagement",
  CircleAutopaySetup: "CircleAutopaySetup",
  CommunityPreferences: "CommunityPreferences",
  BecomeElder: "BecomeElder",
  BookService: "BookService",
  BulkInvites: "BulkInvites",
  ChangePassword: "ChangePassword",
  CircleDetail: "CircleDetail",
  CircleInvite: "CircleInvite",
  CircleVisualizer: "CircleVisualizer",
  CircleVoting: "CircleVoting",
  ProposalDetail: "ProposalDetail",
  CycleDetail: "CycleDetail",
  Circles: "Circles",
  CirclesMain: "CirclesMain",
  CloseCircle: "CloseCircle",
  Community: "Community",
  CommunityBrowser: "CommunityBrowser",
  CommunityFeed: "CommunityFeed",
  CommunityHub: "CommunityHub",
  CommunityMain: "CommunityMain",
  CommunityMemory: "CommunityMemory",
  AIInsights: "AIInsights",
  CreateEvent: "CreateEvent",
  Events: "Events",
  CircleHealth: "CircleHealth",
  ConflictAlert: "ConflictAlert",
  DisputesList: "DisputesList",
  DisputeDetail: "DisputeDetail",
  // Conflict P1 (2026-06-12): new merged screens.
  ConflictCase: "ConflictCase",
  ElderOnboarding: "ElderOnboarding",
  ContributionSuccess: "ContributionSuccess",
  CreateCircleDetails: "CreateCircleDetails",
  CreateCircleInvite: "CreateCircleInvite",
  // Bucket B (Create-a-circle review): CreateCircleSchedule has been
  // superseded by CreateCircleWizardForm. The constant is kept so
  // legacy navigation calls don't fail at the type level until the
  // dead Schedule screen file is deleted in a follow-up cleanup.
  CreateCircleSchedule: "CreateCircleSchedule",
  CreateCircleWizardForm: "CreateCircleWizardForm",
  CreateCircleExpress: "CreateCircleExpress",
  CreateCircleStart: "CreateCircleStart",
  CreateCircleSuccess: "CreateCircleSuccess",
  CreateCommunity: "CreateCommunity",
  CreateDreamPost: "CreateDreamPost",
  CreateGathering: "CreateGathering",
  CreateGoal: "CreateGoal",
  CreateTripListing: "CreateTripListing",
  CreateTripWizard: "CreateTripWizard",
  CreditProfile: "CreditProfile",
  CreditReport: "CreditReport",
  CrossCircleLending: "CrossCircleLending",
  CycleTimeline: "CycleTimeline",
  Dashboard: "Dashboard",
  DecisionHistory: "DecisionHistory",
  DefaultDetail: "DefaultDetail",
  DefaultRecovery: "DefaultRecovery",
  DocumentSubmission: "DocumentSubmission",
  DocumentUpload: "DocumentUpload",
  DomesticSendMoney: "DomesticSendMoney",
  DreamFeed: "DreamFeed",
  DynamicPayout: "DynamicPayout",
  EarlyIntervention: "EarlyIntervention",
  EarlyRepayment: "EarlyRepayment",
  EditStore: "EditStore",
  ElderDashboard: "ElderDashboard",
  ElderNominations: "ElderNominations",
  ElderTrainingHub: "ElderTrainingHub",
  EmailVerification: "EmailVerification",
  ExportData: "ExportData",
  FAQ: "FAQ",
  FeedSettings: "FeedSettings",
  ForgotPassword: "ForgotPassword",
  Gatherings: "Gatherings",
  GoalAchieved: "GoalAchieved",
  GoalActivity: "GoalActivity",
  GoalBItems: "GoalBItems",
  GoalCreateExpress: "GoalCreateExpress",
  GoalDetailV2: "GoalDetailV2",
  GoalEdit: "GoalEdit",
  GoalLinkCircle: "GoalLinkCircle",
  GoalMilestones: "GoalMilestones",
  GoalsHub: "GoalsHub",
  GoalsHubV2: "GoalsHubV2",
  CreateDisbursementMilestones: "CreateDisbursementMilestones",
  GoalDisbursementMilestones: "GoalDisbursementMilestones",
  GoalProviderPayment: "GoalProviderPayment",
  GoalStories: "GoalStories",
  GoalTemplateBrowser: "GoalTemplateBrowser",
  MilestoneVerification: "MilestoneVerification",
  GraduatedEntry: "GraduatedEntry",
  GroupChat: "GroupChat",
  HardshipRequest: "HardshipRequest",
  HelpCenter: "HelpCenter",
  Home: "Home",
  HonorScoreOverview: "HonorScoreOverview",
  HowCirclesWork: "HowCirclesWork",
  IDVerificationStart: "IDVerificationStart",
  InsurancePool: "InsurancePool",
  InterestUnlockedSuccess: "InterestUnlockedSuccess",
  InternationalVerification: "InternationalVerification",
  IssueExposureVouch: "IssueExposureVouch",
  ResolutionCenter: "ResolutionCenter",
  ITINApplicationHelp: "ITINApplicationHelp",
  ITINEducation: "ITINEducation",
  ITINPending: "ITINPending",
  ItineraryBuilder: "ItineraryBuilder",
  JoinCircleByCode: "JoinCircleByCode",
  JoinCircleConfirm: "JoinCircleConfirm",
  JoinCircleSuccess: "JoinCircleSuccess",
  PayoutReceived: "PayoutReceived",
  PayoutHistory: "PayoutHistory",
  JoinConfirm: "JoinConfirm",
  KYCVerification: "KYCVerification",
  KYCHub: "KYCHub",
  KYCDocument: "KYCDocument",
  KycStack: "KycStack",
  LanguageRegion: "LanguageRegion",
  LateContributionDetail: "LateContributionDetail",
  LeaveCircle: "LeaveCircle",
  LegalDocuments: "LegalDocuments",
  LegalDocumentReader: "LegalDocumentReader",
  LimitedMode: "LimitedMode",
  LinkedAccounts: "LinkedAccounts",
  LoanApplication: "LoanApplication",
  LoanCalculator: "LoanCalculator",
  LoanDetails: "LoanDetails",
  LoanMarketplace: "LoanMarketplace",
  Login: "Login",
  MainTabs: "MainTabs",
  MakeContribution: "MakeContribution",
  ManageMembers: "ManageMembers",
  ManageServices: "ManageServices",
  Market: "Market",
  MarketInsight: "MarketInsight",
  MarketMain: "MarketMain",
  Marketplace: "Marketplace",
  MediationCase: "MediationCase",
  DiscoverCircles: "DiscoverCircles",
  MediationTools: "MediationTools",
  LeaveReview: "LeaveReview",
  TripReviews: "TripReviews",
  MoodInsights: "MoodInsights",
  MyTrips: "MyTrips",
  MyTripStatus: "MyTripStatus",
  NearYou: "NearYou",
  NewArrivals: "NewArrivals",
  NotificationPrefs: "NotificationPrefs",
  NotificationsInbox: "NotificationsInbox",
  OnboardingWelcome: "OnboardingWelcome",
  OTP: "OTP",
  OrganizerTripDashboard: "OrganizerTripDashboard",
  OrganizerTripList: "OrganizerTripList",
  OversightDashboard: "OversightDashboard",
  OwnerDashboard: "OwnerDashboard",
  PartialContribution: "PartialContribution",
  ParticipantDetail: "ParticipantDetail",
  ParticipantManager: "ParticipantManager",
  PauseCircle: "PauseCircle",
  PaymentFailed: "PaymentFailed",
  PaymentHistory: "PaymentHistory",
  PaymentReminder: "PaymentReminder",
  PersonalInfo: "PersonalInfo",
  PositionSwap: "PositionSwap",
  // VDF B.7 (2026-06-21) — PostComments route deleted along with
  // DreamPostCommentsScreen. The comment icon now routes to
  // PostDetail with `focusComment: '1'`.
  PostDetail: "PostDetail",
  PostToCommunity: "PostToCommunity",
  PrivacySettings: "PrivacySettings",
  ProfileMain: "ProfileMain",
  ProviderApplication: "ProviderApplication",
  ProviderDashboard: "ProviderDashboard",
  ProviderDetail: "ProviderDetail",
  ProviderDiscovery: "ProviderDiscovery",
  ProviderList: "ProviderList",
  ProviderNetworkVerification: "ProviderNetworkVerification",
  ProviderProfileSetup: "ProviderProfileSetup",
  ProviderTripDashboard: "ProviderTripDashboard",
  ProviderVerification: "ProviderVerification",
  QRCodeDisplay: "QRCodeDisplay",
  QRScanner: "QRScanner",
  QuickCircle: "QuickCircle",
  Referral: "Referral",
  DonationPreferences: "DonationPreferences",
  HostDashboard: "HostDashboard",
  SyncLobby: "SyncLobby",
  SyncRoom: "SyncRoom",
  QuickJoin: "QuickJoin",
  QuickJoinPaymentSuccess: "QuickJoinPaymentSuccess",
  QuickJoinPendingConfirmation: "QuickJoinPendingConfirmation",
  RateBreakdown: "RateBreakdown",
  Remittance: "Remittance",
  RepaymentConfirm: "RepaymentConfirm",
  ReportIssue: "ReportIssue",
  RequestProvider: "RequestProvider",
  ResetPassword: "ResetPassword",
  SavedRecipients: "SavedRecipients",
  SecuritySettings: "SecuritySettings",
  SelectCircleContribution: "SelectCircleContribution",
  ServiceForm: "ServiceForm",
  SetPassword: "SetPassword",
  Settings: "Settings",
  Signup: "Signup",
  SmartCalculator: "SmartCalculator",
  ScoreHub: "ScoreHub",
  Splash: "Splash",
  StoreApplication: "StoreApplication",
  StoreBookings: "StoreBookings",
  StoreDetail: "StoreDetail",
  SubstitutePool: "SubstitutePool",
  StressScoreDashboard: "StressScoreDashboard",
  SupportDream: "SupportDream",
  TaxIDEntry: "TaxIDEntry",
  Tier2Success: "Tier2Success",
  TripPayment: "TripPayment",
  TripPublicPage: "TripPublicPage",
  TripPublishSuccess: "TripPublishSuccess",
  TwoFactorAuth: "TwoFactorAuth",
  UnlockInterestPrompt: "UnlockInterestPrompt",
  UserDreamProfile: "UserDreamProfile",
  VerificationHub: "VerificationHub",
  VerificationOptions: "VerificationOptions",
  VouchMember: "VouchMember",
  VouchSystem: "VouchSystem",
  WalletMain: "WalletMain",
  WalletTransactionSuccess: "WalletTransactionSuccess",
  WebView: "WebView",
  Welcome: "Welcome",
  Withdraw: "Withdraw",
  XnScoreDashboard: "XnScoreDashboard",
  XnScoreHistory: "XnScoreHistory",
} as const;

/**
 * Union of every valid route name. Use in function signatures that take a
 * navigation target — e.g., useTypedNavigation's `navigate(route: RootRoute)`.
 */
export type RootRoute = (typeof Routes)[keyof typeof Routes];
